### ISSUE TITLE
VL53L1_Sat_HelloWorld.ino needs additional clear interrupt with ESP8266?

### ISSUE THREAD

**Issue by dhebbeker** [stm32duino/VL53L1#18] opened 2021-04-29 18:29 UTC
Using the current version (bdd638738f21d48e2067a147063b5e267ecf030c) of the [`VL53L1_Sat_HelloWorld.ino`][3] example I do not get any data from the sensor unless I add an additional clear interrupt.

The program execution is stuck in [this][1] loop:
```cpp
do
{
  status = sensor_vl53l1_sat.VL53L1_GetMeasurementDataReady(&NewDataReady);
} while (!NewDataReady);
```
`status` is always 0 and `!NewDataReady == true`.

But if instead I modify [the end of the setup procedure][2] as follows:
```patch
-   sensor_vl53l1_sat.VL53L1_StartMeasurement();
+   sensor_vl53l1_sat.VL53L1_ClearInterruptAndStartMeasurement();
```

Then everything works as expected: I get correct data.

*But* according to the user manual [UM2133][] rev 6 fig. 6 the original procedure in the code is correct:

 - StartMeasurement in the setup phase
 - ClearInterruptAndStartMeasurement at the end of the loop

So I wonder, where is the error?

I have this issue only with an ESP8266 (NodeMCU board). I also tested it with a Nucleo Board:

| start code at [this][2] line                | Nucleo F401RE                         | NodeMCU                             |
|---------------------------------------------|---------------------------------------|-------------------------------------|
| `VL53L1_StartMeasurement()`                 | works as expected :heavy_check_mark:  | no data :x:                         |
| `VL53L1_ClearInterruptAndStartMeasurement()`| works as expected :heavy_check_mark:  | works as expected :heavy_check_mark:|

In order to use it with the NodeMCU I obviously had to use a different pin for `XSDN_I`.

I know that the [`VL53L1_Sat_HelloWorld.ino`][3] is designed for a Nucleo Board. But due to the abstraction by the Arduino Library I would have expected to work for both boards.

[1]: https://github.com/stm32duino/VL53L1/blob/bdd638738f21d48e2067a147063b5e267ecf030c/examples/VL53L1_Sat_HelloWorld/VL53L1_Sat_HelloWorld.ino#L109
[2]: https://github.com/stm32duino/VL53L1/blob/bdd638738f21d48e2067a147063b5e267ecf030c/examples/VL53L1_Sat_HelloWorld/VL53L1_Sat_HelloWorld.ino#L97
[3]: https://github.com/stm32duino/VL53L1/blob/bdd638738f21d48e2067a147063b5e267ecf030c/examples/VL53L1_Sat_HelloWorld/VL53L1_Sat_HelloWorld.ino
[UM2133]: https://www.st.com/resource/en/user_manual/dm00338304-timeofflight-longdistance-ranging-sensor-with-advanced-multizone-and-multiobject-detection-stmicroelectronics.pdf

**Comment by cparata** [comment] 2021-04-30 06:45
Hi @dhebbeker ,
thanks a lot for your findings. The issue on ESP8266 with the original code is systematic? I mean, does it happen at any boot of the board? Is it always present also if you try to power off and then power on the board?
Best Regards,
Carlo

**Comment by dhebbeker** [comment] 2021-04-30 07:17
Hello @cparata, yes the error appears every time. I also re-did the wiring and it did not change.
Is there is any data which may help to find the error? I can run further tests.

**Comment by cparata** [comment] 2021-04-30 07:38
Hi David,
Unfortunately, I do not have a NodeMCU to make some tests on my side. I will try to ask a feedback to ST experts of VL53L1 component. I let you know. Thanks again for your availability.
Carlo

**Comment by cparata** [comment] 2021-04-30 07:42
@dhebbeker , I forgot to ask you if you have the same issue also with the VL53L1_Sat_HelloWorld_Interrupt sketch. Could you confirm it?

**Comment by dhebbeker** [comment] 2021-05-01 12:53
Hello @cparata, 

in order to test it with the `VL53L1_Sat_HelloWorld_Interrupt.ino` example sketch I had to make *little* adjustments in order to adjust pins, ISR definition and attaching of the ISR (see [this comparison](https://github.com/stm32duino/VL53L1/compare/master...dhebbeker:test/esp8266/v3)). These were necessary because of specifics of the NodeMCU board / ESP8266 MCU. *I addition to that I had to do the same modification as to the non-interrupt example* above:

```patch
-   sensor_vl53l1_sat.VL53L1_StartMeasurement();
+   sensor_vl53l1_sat.VL53L1_ClearInterruptAndStartMeasurement();
```

Without that last modification, not interrupt is triggered. In case I trigger the ISR manually (by pulling the pin low), this is the same as above:
> `status` is always 0 and `!NewDataReady == true`

Only with that change the ISR it triggered and data is received.

I hope these insights can help you or your colleagues to find the issue.

Best regards
David

**Comment by cparata** [comment] 2021-05-03 07:41
Hi @dhebbeker ,
thanks for this last test. Discussing with ST VL53L1 experts, it should be safer to call the "VL53L1_ClearInterruptAndStartMeasurement" instead of "VL53L1_StartMeasurement". So, I'm going to modify the sketches with this call and this way we can close this issue and the pending PR.
Best Regards,
Carlo

**Comment by cparata** [comment] 2021-05-03 07:47
Integrated in the master repo. Thanks @dhebbeker !

**Closed as completed by cparata** 2021-05-03 07:47 UTC

**Comment by dhebbeker** [comment] 2021-05-03 10:49
I am glad this issue could be resolved. :tada: Also is appears to have [helped for the VL53L3CX library](https://github.com/stm32duino/VL53L3CX/issues/7#issuecomment-831174256) as well. 

For the record, the changes were made in c87ec979558af68cb76d3041050e14e8bfedf817 and a23f20005e7ff42a7031122ba8f8da86274f40c0.

Do you have any insights, why this modification was necessary? It deviates from the user manual [UM2133][] rev 6 after all.

Thank you for your help @cparata! :+1: 

[UM2133]: https://www.st.com/resource/en/user_manual/dm00338304-timeofflight-longdistance-ranging-sensor-with-advanced-multizone-and-multiobject-detection-stmicroelectronics.pdf

**Comment by cparata** [comment] 2021-05-04 09:09
Hi David,
the strange thing is that the issue seems present only with ESP boards because with Nucleo board the issue is not present and the software works as expected in the User Manual. I suppose that, when you tested the Polling Mode, you did not connect the interrupt pin of VL53L1, right?
Best Regards,
Carlo

**Comment by dhebbeker** [comment] 2021-05-04 12:08
Hello Carlo,

in contrary, I am quite sure, that I did connect the interrupt pin. But that pin is not configured by the software. Btw: The [directions in the comment](https://github.com/stm32duino/VL53L1/blob/519a3007eb87a3e7da2c0a31c992edbf2f9c4de8/examples/VL53L1_Sat_HelloWorld/VL53L1_Sat_HelloWorld.ino#L42) say to do so.

I expected that the polling example (`VL53L1_Sat_HelloWorld.ino`) does not care about that pin, as it is not configured in software.

Just to make sure, I tested `VL53L1_Sat_HelloWorld.ino` again:

| Test #| based on           | GPIO1 / INT                             | result             |
|-------|--------------------|-----------------------------------------|--------------------|
| 1     | bdd63873 (no fix)  | directly connected to not configured pin|  :x:               |
| 2     | c87ec979 (your fix)| directly connected to not configured pin| :heavy_check_mark: |
| 3     | bdd63873 (no fix)  | not connected                           |  :x:               |
| 4     | bdd63873 (no fix)  | connected via 10k to VDD                |  :x:               |
| 5     | c87ec979 (your fix)| connected via 10k to VDD                |  :heavy_check_mark:|
| 6     | c87ec979 (your fix)| not connected                           |  :heavy_check_mark:|
| 7     | c87ec979 (your fix)| directly connected to not configured pin|  :heavy_check_mark:|

VDD is connected to 3.3V. SCL and SDA to the respective I2C pins. XSHUT is connected to the pin passed to the constructor `sensor_vl53l1_sat`. GND and GND2 to GND. All tests are using a NodeMCU (ESP-12E) and a VL53L1-SATEL board. At the not configured pin I measure 0V.

I would conclude, that it does not make a difference for `VL53L1_Sat_HelloWorld.ino` if GPIO1  / INT is connected.

Best regards
David

**Comment by cparata** [comment] 2021-05-05 06:10
Ok thanks. My concern was about some spurious signals on the interrupt pin that could influence the behavior of the sensor, but your tests show that is not true. So, we keep the fix as it is because we have seen that works for all platforms. Thanks again for your contribution!
